name: 'release'
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: dry run
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '*/2 * * * 5'  # Every Saturday at 1PM UTC
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: decentraland/gh-action-release@0.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: ${{ github.event.inputs.dry_run }}
